deliflow-graph-service:
  ports:
  - 9004:9004/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  entrypoint:
  - bash
  - -c
  - |
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata.rancher.internal/latest/self/container/primary_ip) && echo $$EUREKA_INSTANCE_HOSTNAME && PROFILE=$${ACTIVE_PROFILE:=docker} && java -Xmx512m -Djava.security.egd=file:/dev/./urandom -cp /lib/*:/lean/java/lib/*:/graph-service.jar com.thoughtworks.lean.graph.GraphService --eureka.instance.preferIpAddress=false --spring.profiles.active=$$PROFILE --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: reg.dev.twleansw.com/leansw/graph-service:dev
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
deliflow-code-metrics-service:
  ports:
  - 9003:9003/tcp
  external_links:
  - Default/mongo-server:mongo-server
  - Default/sonar-server:sonar-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  entrypoint:
  - bash
  - -c
  - |
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata.rancher.internal/latest/self/container/primary_ip) && echo $$EUREKA_INSTANCE_HOSTNAME && PROFILE=$${ACTIVE_PROFILE:=docker} && java -Xmx512m -Djava.security.egd=file:/dev/./urandom -cp /lib/*:/lean/java/lib/*:/code-metrics.jar com.thoughtworks.lean.codemetrics.CodeMetricsService --logging.level.sun.net.www.http=DEBUG --eureka.instance.preferIpAddress=false --spring.profiles.active=$$PROFILE --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME" --app.service.home=https://ui.dev.twleansw.com
  image: reg.dev.twleansw.com/leansw/code-metrics:dev
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
deliflow-identity-service:
  ports:
  - 2400:2400/tcp
  external_links:
  - 'Default/mongo-server:'
  - 'Default/gocd-server:'
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  entrypoint:
  - bash
  - -c
  - export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata.rancher.internal/latest/self/container/primary_ip)&& echo $$EUREKA_INSTANCE_HOSTNAME  && PROFILE=$${ACTIVE_PROFILE:=docker} && HOST=$${GOCD_SERVER_HOST:=gocd-server} && PORT=$${GOCD_SERVER_PORT:=8153} && ROOT_PATH=$${GOCD_SERVER_ROOT:=/go} && USERNAME=$${GOCD_USERNAME:=admin} && PASSWORD=$${GOCD_PASSWORD:=badger} && java -Xmx512m -Djava.security.egd=file:/dev/./urandom -cp /lib/*:/lean/java/lib/*:/identity-services.jar com.thoughtworks.lean.identity.IdentityServer --spring.profiles.active=$$PROFILE --gocd.server.host=http://$$HOST:$$PORT$$ROOT_PATH --gocd.server.username=$$USERNAME --gocd.server.password=$$PASSWORD --eureka.instance.preferIpAddress=false  --spring.cloud.config.enable=false --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: reg.dev.twleansw.com/leansw/identity-services:dev
  links:
  - deliflow-discovery-service:eureka-server
deliflow-discovery-service:
  ports:
  - 8761:8761/tcp
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  image: reg.dev.twleansw.com/leansw/discovery-service:dev
  stdin_open: true
deliflow-cd-metrics-service:
  ports:
  - 9001:9001/tcp
  environment:
    RANCHER_ACCESS_SECRET: 14E81ABF45359F074521
    RANCHER_SECRET_KEY: E7xmHz2h22iJWUpf1atDEnqsd2zzv9udHdsQkjjy
    RANCHER_URI: http://rancher-server:8080
  external_links:
  - Default/mongo-server:mongo-server
  - Default/rancher-server:rancher-server
  - Default/gocd-server:gocd-server
  - Default/artifactory-server:artifactory-server
  - Default/rabbitmq-server:rabbitmq-server
  - Default/sonar-server:sonar-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  entrypoint:
  - bash
  - -c
  - |
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata.rancher.internal/latest/self/container/primary_ip) && echo $$EUREKA_INSTANCE_HOSTNAME && PROFILE=$${ACTIVE_PROFILE:=docker} && HOST=$${GOCD_SERVER_HOST:=gocd-server} && PORT=$${GOCD_SERVER_PORT:=8153} && ROOT_PATH=$${GOCD_SERVER_ROOT:=/go} && USERNAME=$${GOCD_USERNAME:=admin} && PASSWORD=$${GOCD_PASSWORD:=badger} && java -Xmx512m -Djava.security.egd=file:/dev/./urandom -cp /lib/*:/lean/java/lib/*:/cd-metrics.jar com.thoughtworks.lean.MetricsServer --rancher.uri=$$RANCHER_URI --rancher.secretKey=$$RANCHER_SECRET_KEY --rancher.accessSecret=$$RANCHER_ACCESS_SECRET --spring.profiles.active=$$PROFILE --gocd.server.host=http://$$HOST:$$PORT$$ROOT_PATH --gocd.server.username=$$USERNAME --gocd.server.password=$$PASSWORD --eureka.instance.preferIpAddress=false --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: reg.dev.twleansw.com/leansw/cd-metrics:dev
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
deliflow-webapp:
  ports:
  - 9900:9900/tcp
  external_links:
  - Default/rabbitmq-server:rabbitmq-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  entrypoint:
  - bash
  - -c
  - |
    export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata.rancher.internal/latest/self/container/primary_ip) && echo $$EUREKA_INSTANCE_HOSTNAME && PROFILE=$${ACTIVE_PROFILE:=docker} && java -Xmx512m -Djava.security.egd=file:/dev/./urandom -cp /lib/*:/lean/java/lib/*:/deliflow-webapp.jar com.thoughtworks.deliflow.DeliFlow --eureka.instance.preferIpAddress=false --spring.profiles.active=$$PROFILE --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: reg.dev.twleansw.com/leansw/deliflow-webapp:dev
  links:
  - deliflow-discovery-service:eureka-server
  stdin_open: true
deliflow-cas-service:
  ports:
  - 8443:8443/tcp
  - 19080:9080/tcp
  external_links:
  - Default/ldap-server:deliflow-ldap-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  image: reg.dev.twleansw.com/leansw/cas-service:dev
deliflow-quartz-service:
  ports:
  - 9005:9005/tcp
  external_links:
  - Default/mongo-server:mongo-server
  - Default/sonar-server:sonar-server
  - Default/gocd-server:gocd-server
  - Default/rancher-server:rancher-server
  labels:
    io.rancher.container.pull_image: always
    io.ranhcer.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: host_env=dev
  tty: true
  entrypoint:
  - bash
  - -c
  - export EUREKA_INSTANCE_HOSTNAME=$$(curl http://rancher-metadata.rancher.internal/latest/self/container/primary_ip) && echo $$EUREKA_INSTANCE_HOSTNAME && PROFILE=$${ACTIVE_PROFILE:=docker} && HOST=$${GOCD_SERVER_HOST:=gocd-server} && PORT=$${GOCD_SERVER_PORT:=8153} && ROOT_PATH=$${GOCD_SERVER_ROOT:=/go} && USERNAME=$${GOCD_USERNAME:=admin} && PASSWORD=$${GOCD_PASSWORD:=badger} && java -Xmx512m -Djava.security.egd=file:/dev/./urandom -cp /lib/*:/lean/java/lib/*:/quartz-service.jar com.thoughtworks.lean.quartz.QuartzService --spring.profiles.active=$$PROFILE --gocd.server.host=http://$$HOST:$$PORT$$ROOT_PATH --gocd.server.username=$$USERNAME --gocd.server.password=$$PASSWORD --eureka.instance.preferIpAddress=false --eureka.instance.hostname="$$EUREKA_INSTANCE_HOSTNAME"
  image: reg.dev.twleansw.com/leansw/quartz-service:dev
  links:
  - deliflow-discovery-service:eureka-server

