deliflow-graph-service:
  scale: 1
deliflow-code-metrics-service:
  scale: 1
deliflow-identity-service:
  scale: 1
deliflow-discovery-service:
  scale: 1
deliflow-cd-metrics-service:
  scale: 1
deliflow-webapp:
  scale: 1
deliflow-cas-service:
  scale: 1
deliflow-quartz-service:
  scale: 1

